data test;
infile "D:\test.txt" dlm='/' firstobs=2;
input student section test1 test2 test3 test4;
run;
data one1;
set test;
if section=1 then do;
test5=0;
test6=0;
test5=test1-10;
test6=test2-14;
end;
else do;
test5=0;
test6=0;
test5=test1+3;
test6=test2+5;
end;
run;
data one2;
set one1;
array a{6} test1-test6;
if section=1 then do i=1 to 6;
retain total 0;
total=total+a{i};
output;
end;
run;
data preg;
infile "D:\preg.txt" expandtabs firstobs=2;
input name$ preg_num date;
run;
data expo;
infile"D:\expo.txt" expandtabs firstobs=2;
input name$ date exposlvl$;
run;
proc sort data=preg;
by name;
run;
proc sort data=expo;
by name;
run;
data bothid;
merge preg(rename=(date=PREG_DATE)) expo(rename=(date=EXPO_DATE));
by name;
run;
proc import datafile="D:\timerec.xlsx" dbms=xlsx out=timerec;
getnames=yes;
run;
data three1;
set timerec;
label employee='고용인'
		phase='분석단계'
		hours='시간';
run;
data emp1 emp2;
set timerec;
if employee = Chen then output emp1;
else output emp2;
run;
data three3;
set timerec;
retain hoursum 0;
hoursum=hoursum+hours;
run;


data grunfeld;
infile"D:\grunfeld.txt" expandtabs firstobs=1;
input sort$ invest stock value@@;
run;
proc sort data=grunfeld;
by sort;
run;
proc means data=grunfeld;
by sort;
run;
data four;
do x=-1 to 20;
pdf=pdf("normal",x,10,2);
output;
end;
run;
proc gplot data=four;
symbol i=spline v=none;
plot pdf*x;
run;


