data test;
infile "D:\test.txt" expandtabs firstobs=2;
input student section test1 test2 test3 test4;
run;
data one;
set test;
if section=1 then do;
test5=test1-10;
test6=test2-14;
end;
else do;
test5=test1+3; test6=test2+5;
end;
run;
data one2;
set one;
if section=2 then delete;
array arr{6} test1-test6;
total=0;
do i=1 to 6;
total=arr{i}+total;
end;
run;

data preg;
infile "D:\preg.txt" expandtabs firstobs=2;
input name$ preg_num date;
rename date=preg_date;
run;
data expo;
infile "D:\expo.txt" expandtabs firstobs=2;
input name$ date exposlvl$;
rename date=expo_date;
run;
data bothid;
merge preg expo;
run;
proc sort data=bothid;
by name;
run;
proc freq data=bothid;
preg_date*expo_date/listsparse;
run;
proc import datafile="D:\timerec.xlsx" out =imerec dbms=xlsx;
getnames=yes;
run;
data two;
set imerec;
label employee='고용인'
phase='분석단계'
hours='시간';
run;

data emp1 emp2;
set two;
if employee='Stewart' then output emp2;
else output emp1;
drop employee;
run;
data three3;
set emp1;
retain hoursum;
hoursum=hoursum+hours;
drop hours;
run;
data grunfeld;
infile "d:\grunfeld.txt" expandtabs firstobs=1;
input sort$ invest stock value;
run;
proc mean data=grunfeld;
run;

proc gplot;
x=1-20;
a=pdf('normal',x,10,2);
plot a*x;
symbol i=spline v=none;
run;
