data test;
infile "C:\Users\a29\Desktop\test.txt"  dlm='/' firstobs=2;
input student section test1 test2 test3 test4;
run;
data test_1;
set test;
if section=1 then do;
test5=test1-10;
test6=test2-14;
output;
end;
else do section=2;
test5=test1+3;
test6=test2+5;
output;
end;
run;
data test_2;
set test_1(where=(section=1));
array x{6} test1-test6;
total=0;
do i=1 to 6;
total=total+x{i};
end;
drop i;
run;
data preg;
infile "C:\Users\a29\Desktop\preg.txt" firstobs=2;
input name$ preg_num date;
run;
data expo;
infile "C:\Users\a29\Desktop\expo.txt" firstobs=2;
input name$ date exposlvl$;
run;
data bothid ;
merge preg(rename=(date=preg_date))
		   expo(rename=(date=expo_date));
		   run;
proc import datafile="C:\Users\a29\Desktop\timerec.xlsx" out=timerec dbms=xlsx replace;
getnames=yes;
run;
data timerec_1;
set timerec;
label employee='고용인'
		 phase='분석단계'
		 hours='시간'
		 ;
		 run;
data emp2 emp1;
set timerec;
if employee='Stewart' then output emp2;
else output emp1;
run;
data grunfeld;
infile "C:\Users\a29\Desktop\grunfeld.txt" ;
input sort$ invest srock value @@;
run;
proc sort data=grunfeld out=grunfeld;
by sort;
run;
proc means data=grunfeld  ;
var invest srock value;
by sort;
run;
data pdf;
do x=1 to 20;
p=pdf("normal",x,10,2);
output;
end;
run;
proc gplot data=pdf;
symbol i=spline v=none;
plot p*x;
run;
