data test;
infile "C:\Users\a55\Downloads\test.txt" dlm='/' firstobs=2;
input student section test1 test2 test3 test4;
run; 
data test10;
set test;
if section = 1 then do;
test5 = test1-10;
test6 = test2 -14;
end;
else do;
test5 = test1 +3;
test6 = test2 +5;
end;
run;
data test11;
set test10(where=(section=1));
array test{6} test1-test6;
total = 0;
do i=1 to 6;
total = total + test{i};
end;
drop i;
run;

data preg;
infile "C:\Users\a55\Downloads\preg.txt" dlm=' ' firstobs=2;
input name$ preg_num date;
run;
data expo;
infile "C:\Users\a55\Downloads\expo.txt" dlm=' ' firstobs=2;
input name$ date exposlvl$;
run;
proc sort data = preg;
by name;
run;
proc sort data = expo;
by name;
run;
data bothid;
merge preg(rename=(date=PREG_DATE) ) expo(rename=(date=EXPO_DATE));
by name;
if PREG_DATE ='.' or EXPO_DATE ='.' then delete;
run;
proc import datafile = "C:\Users\a55\Downloads\timerec.xlsx" out= timerec dbms=xlsx replace;
getnames=yes;
run;

data timerec1;
set timerec;
label employee = '고용인'
phase = '분석단계'
hours = '시간';
run;
data emp1 emp2;
set timerec;
if employee = 'Stewart' then output emp2;
else output emp1;
drop employee;
run;
proc sort data= emp1;
by phase;
run;
proc sort data = emp2;
by phase;
run;


data q1;
set emp1;
retain hoursum 0;
if phase = 'Analysis' then do;
hoursum = hoursum + hours;
if last.phase = 1 then hoursum=0;
end;
else if phase = 'Coding' then do;
hoursum = hoursum + hours;
if last.phase = 1 then hoursum=0;
end;
else hoursum = hoursum + hours;
drop hours;
run;
data grunfeld;
infile "C:\Users\a55\Downloads\grunfeld.txt"  dlm="  ";
input sort$ invest stock value @@;
run;
proc sort data=grunfeld;
by sort;
run;
proc means data=grunfeld;
var invest stock value;
by sort;
run;

data q;
do x = 1 to 20;
pdf = pdf("normal",x,10,2);
output;
end;
run;
proc gplot data=q;
symbol i=spline v=none;
plot pdf*x;
run;
